name: Test - this is a test workflow

on:
  push:
    branches:
      - test
  pull_request:
    types: [opened, closed, reopened, synchronize, edited]
    branches:
      - test

jobs:
  print_github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: print pr title
      #   run: echo "${{ github.event.pull_request.title }}"
      - name: Perform HTTP Request
        run: |
          title=$(jq -r  <<< "${{ toJson(github.event.pull_request.title) }}")

          echo "Title: $title"

          # Replace double quotes with escaped double quotes
          escaped_double_quotes="${title//\"/\\\"}"

          echo "Escaped title: $escaped_double_quotes"

          # Replace single quotes with escaped single quotes
          escaped_single_quotes="${escaped_double_quotes//\'/\\\'}"

          echo "Escaped title: $escaped_single_quotes"

          curl -X POST \
              -H "Content-Type: application/json" \
              -d "{
                  \"title\": \"$escaped_single_quotes\",
                  \"creator\": \"${{ github.event.pull_request.user.login }}\",
                  \"url\": \"${{ github.event.pull_request.html_url }}\"   
                }" \
              https://www.example.com/api/v1/pull_request
        # if_closed_pr:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   steps:
  #     - name: say hello
  #       run: echo "This is a merged pull request"
