name: Test - this is a test workflow

on:
  push:
    branches:
      - test
  pull_request:
    types: [closed]

jobs:
  print_github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  if_closed_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: say hello
        run: echo "This is a merged pull request"
